package_assets: on
embed_assets: on
javascript_compressor: closure
compressor_options:
  compilation_level: "SIMPLE_OPTIMIZATIONS"

stylesheets:
  style:
    - public/stylesheets/style.css
  style_ie:
    - public/stylesheets/ie.css

javascripts:
  application:
    - public/javascripts/prototype.js
    - public/javascripts/s2.js
    - public/javascripts/modernizr.js
    - public/javascripts/application.js