package_assets: on
embed_assets: on
javascript_compressor: closure
compressor_options:
  compilation_level: "SIMPLE_OPTIMIZATIONS"

stylesheets:
  sublime:
    - public/stylesheets/sublime/video/style.css