development:
  adapter: mongodb
  hostname: localhost
  database: jilion-dev
  
test:
  adapter: mongodb
  hostname: localhost
  database: jilion-test
  
production:
  adapter: mongodb
  hostname: localhost
  database: jilion-prod