development:
  adapter: mongodb
  database: jilion-dev
  host: localhost

test:
  adapter: mongodb
  database: jilion-test
  host: localhost

production:
  adapter: mongodb
  database: jilion-prod
  host: localhost
