development_and_test_sessions: &development_and_test_sessions
  hosts:
    - localhost:27017
  options:
    retry_interval: 0
    max_retries: 1

development:
  sessions:
    default:
      <<: *development_and_test_sessions
      database: jilion-development

test:
  sessions:
    default:
      <<: *development_and_test_sessions
      database: jilion-test

production: &production
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        pool_size: 10
        safe: true

staging:
  <<: *production
