<%
  # http://mislav.uniqpath.com/rails/branching-the-database-along-with-your-code/
  branch = `git symbolic-ref HEAD 2>/dev/null`.chomp.sub('refs/heads/', '')
  suffix = `git config --bool branch.#{branch}.database`.chomp == 'true' ? "_#{branch}" : ""
%>

development:
  host: localhost
  database: jilion_dev<%= suffix %>

test:
  host: localhost
  database: jilion_test<%= suffix %>

staging:
  uri: <%= ENV['MONGOHQ_URL'] %>
  persist_in_safe_mode: true

production:
<% if ARGV.join.include? 'assets:precompile' %>
  # make rake asset:precompile work
  preload_models: false
  host: localhost
  database: jilion_dev<%= suffix %>
<% else %>
  uri: <%= ENV['MONGOHQ_URL'] %>
  persist_in_safe_mode: true
<% end %>
